//! `cracked_hashes` table: every (task_id, hash) → plaintext result the
//! coord has ever recorded. Doubles as the system-wide potfile because
//! the unique index on (task_id, hash) deduplicates per-task while
//! `check_potfile` scans across tasks.

use anyhow::{Context, Result};
use crack_common::models::CrackedHash;
use sqlx::{Row, SqlitePool};
use uuid::Uuid;

use super::{now_iso, row_to_cracked};

pub async fn insert_cracked_hash(
    pool: &SqlitePool,
    task_id: Uuid,
    hash: &str,
    plaintext: &str,
    worker_id: &str,
) -> Result<bool> {
    let now = now_iso();

    let result = sqlx::query(
        "INSERT OR IGNORE INTO cracked_hashes (task_id, hash, plaintext, worker_id, cracked_at)
         VALUES (?1, ?2, ?3, ?4, ?5)",
    )
    .bind(task_id.to_string())
    .bind(hash)
    .bind(plaintext)
    .bind(worker_id)
    .bind(&now)
    .execute(pool)
    .await
    .context("inserting cracked hash")?;

    // True if a new row was inserted (i.e. not a duplicate).
    Ok(result.rows_affected() > 0)
}

pub async fn get_cracked_for_task(pool: &SqlitePool, task_id: Uuid) -> Result<Vec<CrackedHash>> {
    let rows =
        sqlx::query("SELECT * FROM cracked_hashes WHERE task_id = ?1 ORDER BY cracked_at ASC")
            .bind(task_id.to_string())
            .fetch_all(pool)
            .await
            .context("fetching cracked hashes for task")?;

    rows.iter().map(row_to_cracked).collect()
}

#[allow(dead_code)]
pub async fn check_potfile(pool: &SqlitePool, hash: &str) -> Result<Option<CrackedHash>> {
    let row = sqlx::query("SELECT * FROM cracked_hashes WHERE hash = ?1 LIMIT 1")
        .bind(hash)
        .fetch_optional(pool)
        .await
        .context("checking potfile for hash")?;

    match row {
        Some(ref r) => Ok(Some(row_to_cracked(r)?)),
        None => Ok(None),
    }
}

#[allow(dead_code)]
pub async fn get_all_cracked_plaintexts(pool: &SqlitePool) -> Result<Vec<(String, String)>> {
    let rows = sqlx::query("SELECT hash, plaintext FROM cracked_hashes ORDER BY cracked_at ASC")
        .fetch_all(pool)
        .await
        .context("fetching all cracked plaintexts")?;

    Ok(rows
        .iter()
        .map(|r| {
            let hash: String = r.get("hash");
            let plaintext: String = r.get("plaintext");
            (hash, plaintext)
        })
        .collect())
}

#[allow(dead_code)]
pub async fn count_total_cracked(pool: &SqlitePool) -> Result<u64> {
    let row = sqlx::query("SELECT COUNT(*) as cnt FROM cracked_hashes")
        .fetch_one(pool)
        .await
        .context("counting total cracked")?;

    let count: i64 = row.get("cnt");
    Ok(count as u64)
}

/// Potfile stats: (total_cracked, unique_hashes, unique_plaintexts).
pub async fn get_potfile_stats(pool: &SqlitePool) -> Result<(u64, u64, u64)> {
    let row = sqlx::query(
        "SELECT
           COUNT(*) as total,
           COUNT(DISTINCT hash) as unique_hashes,
           COUNT(DISTINCT plaintext) as unique_plaintexts
         FROM cracked_hashes",
    )
    .fetch_one(pool)
    .await
    .context("fetching potfile stats")?;

    Ok((
        row.get::<i64, _>("total") as u64,
        row.get::<i64, _>("unique_hashes") as u64,
        row.get::<i64, _>("unique_plaintexts") as u64,
    ))
}

/// Get recently cracked hashes across all tasks (for TUI).
pub async fn get_recent_cracked(pool: &SqlitePool, limit: u32) -> Result<Vec<CrackedHash>> {
    let rows = sqlx::query("SELECT * FROM cracked_hashes ORDER BY cracked_at DESC LIMIT ?1")
        .bind(limit)
        .fetch_all(pool)
        .await
        .context("fetching recent cracked hashes")?;

    rows.iter().map(row_to_cracked).collect()
}

/// Export all cracked plaintexts as a list of strings.
pub async fn get_all_plaintexts(pool: &SqlitePool) -> Result<Vec<String>> {
    let rows = sqlx::query("SELECT DISTINCT plaintext FROM cracked_hashes ORDER BY plaintext ASC")
        .fetch_all(pool)
        .await
        .context("fetching all plaintexts")?;

    Ok(rows
        .iter()
        .map(|r| r.get::<String, _>("plaintext"))
        .collect())
}

/// Every cracked hash for tasks belonging to the given campaign. Joins
/// through `tasks.campaign_id`, ordered by `cracked_at`. Used by the
/// pattern analyzer to derive new masks for AutoGenerated phases.
pub async fn get_cracked_hashes_for_campaign(
    pool: &SqlitePool,
    campaign_id: Uuid,
) -> Result<Vec<CrackedHash>> {
    let rows = sqlx::query(
        "SELECT ch.* FROM cracked_hashes ch
         JOIN tasks t ON t.id = ch.task_id
         WHERE t.campaign_id = ?1
         ORDER BY ch.cracked_at ASC",
    )
    .bind(campaign_id.to_string())
    .fetch_all(pool)
    .await
    .context("fetching cracked hashes for campaign")?;

    rows.iter().map(row_to_cracked).collect()
}
