use crack_common::models::{CampaignTemplate, MaskEntry, PhaseConfig, TemplatePhase};

pub fn builtin_templates() -> Vec<CampaignTemplate> {
    vec![
        ntlm_standard(),
        wpa_quick(),
        generic_quick(),
    ]
}

fn me(mask: &str) -> MaskEntry {
    MaskEntry {
        mask: mask.to_string(),
        custom_charsets: None,
        increment: false,
    }
}

fn ntlm_standard() -> CampaignTemplate {
    CampaignTemplate {
        name: "ntlm-standard".to_string(),
        description: "NTLM (mode 1000) — PINs, targeted patterns, iteration, brute-force".to_string(),
        hash_mode: Some(1000),
        phases: vec![
            TemplatePhase {
                name: "PIN sweep".to_string(),
                config: PhaseConfig::MultiMask {
                    masks: vec![
                        me("?d?d?d?d?d?d"),
                        me("?d?d?d?d?d?d?d?d"),
                        me("?d?d?d?d?d?d?d?d?d?d"),
                    ],
                },
            },
            TemplatePhase {
                name: "Common patterns".to_string(),
                config: PhaseConfig::MultiMask {
                    masks: vec![
                        me("?l?l?l?l?l?l?l?l"),               // all lowercase 8
                        me("?u?l?l?l?l?l?d?d"),               // Ullllldd (Password12)
                        me("?u?l?l?l?l?l?l?d"),               // Ullllllld
                        me("?u?l?l?l?l?l?d?d?d?d"),           // Ulllldddd (Summer2024)
                        me("?u?l?l?l?l?l?l?l?d"),             // Ulllllllld
                        me("?l?l?l?l?l?l?d?d?d?d"),           // lllllldddd
                        me("?u?l?l?l?l?l?d?d?d?d?s"),         // Ulllllddds (Summer2024!)
                        me("?u?l?l?l?l?l?l?d?d?d?d"),         // Ulllllldddd
                        me("?l?l?l?l?l?l?l?l?l"),             // all lowercase 9
                        me("?u?l?l?l?l?l?l?l?d?d"),           // Ulllllllldd
                        me("?d?d?d?d?d?d?d"),                 // 7-digit PIN
                        me("?d?d?d?d?d?d?d?d?d"),             // 9-digit PIN
                        me("?u?l?l?l?l?d?d"),                 // Ulllldd
                        me("?u?l?l?l?l?l?l?l"),               // Ulllllll
                        me("?l?l?l?l?l?d?d?d"),               // llllldddd
                        me("?u?l?l?l?d?d?d?d"),               // Ullldddd
                        me("?u?l?l?l?l?l?l?d?d"),             // Ulllllldd
                        me("?l?l?l?l?l?l?l?d?d"),             // llllllldd
                        me("?u?l?l?l?l?l?l?l?l?d"),           // Ulllllllld
                        me("?l?l?l?l?l?l?d?d"),               // lllllldd
                        me("?u?l?l?l?l?l?s"),                 // Ullllls
                        me("?u?l?l?l?l?l?l?d?d?s"),           // Ulllllldds
                        me("?u?l?l?l?l?l?l?l?d?d?d?d"),       // Ulllllllldddd
                        me("?u?l?l?l?l?l?l?l?d?s"),           // Ulllllllds
                        me("?u?l?l?l?l?l?l?l?l?d?d"),         // Ullllllllldd
                        me("?l?l?l?l?l?l?l?l?d?d"),           // lllllllldd
                    ],
                },
            },
            TemplatePhase {
                name: "Iteration 1".to_string(),
                config: PhaseConfig::AutoGenerated {
                    min_sample_size: 20,
                    max_masks: 15,
                },
            },
            TemplatePhase {
                name: "Short brute".to_string(),
                config: PhaseConfig::ExpandingBrute {
                    charset: "?a".to_string(),
                    min_length: 1,
                    max_length: 6,
                    custom_charsets: None,
                },
            },
            TemplatePhase {
                name: "Iteration 2".to_string(),
                config: PhaseConfig::AutoGenerated {
                    min_sample_size: 30,
                    max_masks: 10,
                },
            },
            TemplatePhase {
                name: "Extended brute".to_string(),
                config: PhaseConfig::ExpandingBrute {
                    charset: "?a".to_string(),
                    min_length: 7,
                    max_length: 8,
                    custom_charsets: None,
                },
            },
        ],
    }
}

fn wpa_quick() -> CampaignTemplate {
    CampaignTemplate {
        name: "wpa-quick".to_string(),
        description: "WPA/WPA2 (mode 22000) — 8-digit PIN, common 8-char, iteration".to_string(),
        hash_mode: Some(22000),
        phases: vec![
            TemplatePhase {
                name: "8-digit PIN".to_string(),
                config: PhaseConfig::StaticMask {
                    mask: "?d?d?d?d?d?d?d?d".to_string(),
                    custom_charsets: None,
                },
            },
            TemplatePhase {
                name: "Common 8-char".to_string(),
                config: PhaseConfig::MultiMask {
                    masks: vec![
                        me("?l?l?l?l?l?l?l?l"),
                        me("?u?l?l?l?l?l?l?d"),
                        me("?u?l?l?l?l?l?d?d"),
                    ],
                },
            },
            TemplatePhase {
                name: "Iteration".to_string(),
                config: PhaseConfig::AutoGenerated {
                    min_sample_size: 5,
                    max_masks: 5,
                },
            },
        ],
    }
}

fn generic_quick() -> CampaignTemplate {
    CampaignTemplate {
        name: "generic-quick".to_string(),
        description: "Generic — PINs, common patterns, iteration, brute-force".to_string(),
        hash_mode: None,
        phases: vec![
            TemplatePhase {
                name: "PIN sweep".to_string(),
                config: PhaseConfig::MultiMask {
                    masks: vec![
                        me("?d?d?d?d?d?d"),
                        me("?d?d?d?d?d?d?d?d"),
                    ],
                },
            },
            TemplatePhase {
                name: "Common patterns".to_string(),
                config: PhaseConfig::MultiMask {
                    masks: vec![
                        me("?l?l?l?l?l?l?l?l"),
                        me("?u?l?l?l?l?l?d?d"),
                        me("?u?l?l?l?l?l?l?d"),
                        me("?u?l?l?l?l?l?d?d?d?d"),
                        me("?l?l?l?l?l?l?d?d?d?d"),
                        me("?u?l?l?l?l?l?l?l?d"),
                        me("?u?l?l?l?l?l?l?d?d"),
                        me("?l?l?l?l?l?l?l?l?l"),
                        me("?u?l?l?l?l?l?d?d?d?d?s"),
                        me("?u?l?l?l?l?l?l?d?d?d?d"),
                        me("?u?l?l?l?l?d?d"),
                        me("?l?l?l?l?l?d?d?d"),
                    ],
                },
            },
            TemplatePhase {
                name: "Iteration 1".to_string(),
                config: PhaseConfig::AutoGenerated {
                    min_sample_size: 10,
                    max_masks: 10,
                },
            },
            TemplatePhase {
                name: "Full brute".to_string(),
                config: PhaseConfig::ExpandingBrute {
                    charset: "?a".to_string(),
                    min_length: 1,
                    max_length: 7,
                    custom_charsets: None,
                },
            },
            TemplatePhase {
                name: "Iteration 2".to_string(),
                config: PhaseConfig::AutoGenerated {
                    min_sample_size: 20,
                    max_masks: 10,
                },
            },
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn test_builtin_templates_unique_names() {
        let templates = builtin_templates();
        let names: HashSet<&str> = templates.iter().map(|t| t.name.as_str()).collect();
        assert_eq!(names.len(), templates.len(), "template names must be unique");
    }

    #[test]
    fn test_templates_have_phases() {
        for t in builtin_templates() {
            assert!(!t.phases.is_empty(), "template '{}' has no phases", t.name);
        }
    }

    #[test]
    fn test_every_template_has_autogenerated() {
        for t in builtin_templates() {
            let has_auto = t.phases.iter().any(|p| matches!(p.config, PhaseConfig::AutoGenerated { .. }));
            assert!(has_auto, "template '{}' should have at least one AutoGenerated phase", t.name);
        }
    }
}
